version: '3.9'

services:
  backend:
    image: qortex-backup-restore
    build:
      context: ./
      args:
        - PROJECT_NAME=%%project-name%%
        - DB_CONTAINER_NAME=%%project-name%%-db
        - MEDIA_CONTAINER_NAME=%%project-name%%-backend

        - DB_NAME=%%database-name%%
        - DB_USERNAME=%%database-username%%
        - DB_PASSWORD=%%database-password%%

        - S3_ACCESS_KEY_ID=%%s3-access-key-id%%
        - S3_SECRET_ACCESS_KEY=%%s3-secret-access-key%%
        - S3_ENDPOINT_URL=%%s3-endpoint-url%%
        - S3_BUCKET_NAME=%%s3-bucket-name%%

    container_name: qortex-backup-restore
